version: '3'
services:
  apache-php:
    build:
      context: docker-compose
      dockerfile: php/Dockerfile
#    volumes:
#    - ./src:/var/www/html
    ports:
    - "80:80"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    build:
      context: docker-compose
      dockerfile: sql/Dockerfile
    ports:
    - "3306:3306"

#    image: mysql:5.7
#    volumes:
#    - ./mysql:/var/lib/mysql
#    - ./cfg:/etc/mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: wishlist
#      MYSQL_USER: phpuser
#      MYSQL_PASSWORD: password